name: Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  ghcr:
    name: ${{ github.ref == 'refs/heads/main' && 'Build and Push' || 'Test Build' }}
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Login to ghcr.io
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ${{ github.ref == 'refs/heads/main' && 'Build and Push' || 'Test Build' }}
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
            push: ${{ github.ref == 'refs/heads/main' }}
            tags: ghcr.io/biaw/ookla-speedtest-server:latest
