name: Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  ghcr:
    name: ${{ github.ref == 'refs/heads/main' && 'Build and Push' || 'Test Build' }}
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Login to ghcr.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ${{ github.ref == 'refs/heads/main' && 'Build and Push' || 'Test Build' }}
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
            push: ${{ github.ref == 'refs/heads/main' }}
            tags: ghcr.io/biaw/ookla-speedtest-server:latest
